FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    curl \
    iputils-ping \
    slowhttptest \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./attacker /app

CMD ["tail", "-f", "/dev/null"]