FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    curl \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./client /app

RUN python3 -m venv ./venv

RUN source ./venv/bin/activate

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

ENV PATH="/app/venv/bin:$PATH"

CMD ["tail", "-f", "/dev/null"]